num1=int(input("first number:"))
num2=int(input("second number:"))
print("sum is {0}".format(num1+num2))
print("cha is {0}".format(num1-num2))
print("gob is {0}".format(num1*num2))
print("nanumyeon {0}".format(num1/num2))
